const CardData = [
    {
        id: 1,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 2,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 3,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 4,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 5,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 6,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 7,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 8,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 9,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 1,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 2,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 3,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 4,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 5,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 6,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 7,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 8,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 9,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 1,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 2,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 3,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 4,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 5,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 6,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 7,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 8,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 9,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    },
    {
        id: 9,
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoBHUrA61lCdeEyVI7E3kj8tO6yEvZi4apgw&usqp=CAU",
        name:"Google Ad's",
        description:"Google Ad's description and all stuffs",
        buttonName:"Create Project",
    }
    
]

export default CardData